name: Aprendiendo triggers
run-name: ¡Estoy aprendiendo GitHub Actions Triggers!
on: 
  [pull_request] 

    
    
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python main.py
